server:
  port: 8080
  servlet:
    context-path: /api
spring:
  datasource:
    url: jdbc:postgresql://c5cnr847jq0fj3.cluster-czrs8kj4isg7.us-east-1.rds.amazonaws.com:5432/d1kdcmoah5npok
    username: uvs6na7c524um
    password: pfbe4b01acec25b74b6f9b658ad23f36cb60a1bb148554c0ea131894f68c2a80b
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc.batch_size: 20
        order_inserts: true
        order_updates: true
        batch_versioned_data: true
  cache:
    type: simple
    cache-names:
      - userProjects
      - projectDetails
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.ssl.trust: smtp.gmail.com

# Frontend URL configuration
app:
  frontend:
    url: ${FRONTEND_URL}

jwt:
  signerKey: ${JWT_SIGNER_KEY}
  valid-duration: 86400 #seconds
  refreshable-duration: 360000

springdoc:
  api-docs:
    enabled: true
    path: /api-docs

aws:
  s3:
    bucket: ${AWS_BUCKET}
    region: ${AWS_REGION}
    access-key: ${AWS_ACCESS_KEY}
    secret-key: ${AWS_SECRET_KEY}
    prefix: attachments/