name: Deploy Spring Boot to AWS Elastic Beanstalk

on:
    push:
        branches:
        - main

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-java@v4
              with:
                  distribution: 'corretto'
                  java-version: '21'
            - run: java BackendApplication.java

            - name: Build with Maven
              run: mvn clean package --file backend/pom.xml -DskipTests

            - name: Deploy to AWS Elastic Beanstalk
              uses: einaregilsson/beanstalk-deploy@v22
              with:
                application_name: 'Teamer-backend'
                environment_name: 'Teamer-backend-env'
                version_label: ${{ github.sha }}
                aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                region: ap-southeast-1
                deployment_package: backend/target/backend-0.0.1-SNAPSHOT.jar
